// デモモード用のモックデータ

export const DEMO_USER = {
  id: 'demo-user-001',
  email: 'demo@example.com',
  name: 'デモユーザー',
  avatar_url: null,
  plan: 'デモ',
  role: 'owner',
  company_id: 'demo-company-001',
  company_name: 'デモ株式会社',
}

export const DEMO_EMPLOYEES = [
  {
    id: 'demo-emp-001',
    email: 'demo@example.com',
    display_name: 'デモユーザー',
    role: 'owner',
    company_id: 'demo-company-001',
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-emp-002',
    email: 'tanaka@example.com',
    display_name: '田中 太郎',
    role: 'admin',
    company_id: 'demo-company-001',
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-emp-003',
    email: 'suzuki@example.com',
    display_name: '鈴木 花子',
    role: 'member',
    company_id: 'demo-company-001',
    created_at: new Date().toISOString(),
  },
]

export const DEMO_BUSINESS_CARDS = [
  {
    id: 'demo-card-001',
    full_name: '山田 一郎',
    full_name_kana: 'ヤマダ イチロウ',
    company_name: '株式会社テクノロジー',
    department: '営業部',
    position: '部長',
    email: 'yamada@tech-corp.co.jp',
    phone: '03-1234-5678',
    mobile: '090-1234-5678',
    postal_code: '100-0001',
    address: '東京都千代田区丸の内1-1-1',
    website: 'https://tech-corp.co.jp',
    employee_id: 'demo-emp-001',
    company_id: 'demo-company-001',
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    image_url: null,
    tags: ['営業', '重要'],
    memo: '次回ミーティングは来週火曜日',
  },
  {
    id: 'demo-card-002',
    full_name: '佐藤 美咲',
    full_name_kana: 'サトウ ミサキ',
    company_name: '株式会社イノベーション',
    department: 'マーケティング部',
    position: 'マネージャー',
    email: 'sato@innovation.co.jp',
    phone: '03-9876-5432',
    mobile: '080-9876-5432',
    postal_code: '150-0002',
    address: '東京都渋谷区渋谷2-2-2',
    website: 'https://innovation.co.jp',
    employee_id: 'demo-emp-001',
    company_id: 'demo-company-001',
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    image_url: null,
    tags: ['マーケティング'],
    memo: null,
  },
  {
    id: 'demo-card-003',
    full_name: '高橋 健太',
    full_name_kana: 'タカハシ ケンタ',
    company_name: '株式会社クリエイト',
    department: '開発部',
    position: 'エンジニア',
    email: 'takahashi@create.co.jp',
    phone: '06-1111-2222',
    mobile: '070-1111-2222',
    postal_code: '530-0001',
    address: '大阪府大阪市北区梅田3-3-3',
    website: 'https://create.co.jp',
    employee_id: 'demo-emp-002',
    company_id: 'demo-company-001',
    created_at: new Date(Date.now() - 86400000 * 14).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 14).toISOString(),
    image_url: null,
    tags: ['開発', 'パートナー'],
    memo: 'システム連携の件で相談予定',
  },
  {
    id: 'demo-card-004',
    full_name: '中村 優子',
    full_name_kana: 'ナカムラ ユウコ',
    company_name: '株式会社デザインワークス',
    department: 'デザイン部',
    position: 'ディレクター',
    email: 'nakamura@design-works.co.jp',
    phone: '03-3333-4444',
    mobile: '090-3333-4444',
    postal_code: '106-0032',
    address: '東京都港区六本木4-4-4',
    website: 'https://design-works.co.jp',
    employee_id: 'demo-emp-001',
    company_id: 'demo-company-001',
    created_at: new Date(Date.now() - 86400000 * 30).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 30).toISOString(),
    image_url: null,
    tags: ['デザイン'],
    memo: null,
  },
  {
    id: 'demo-card-005',
    full_name: '小林 誠',
    full_name_kana: 'コバヤシ マコト',
    company_name: '株式会社ファイナンス',
    department: '経理部',
    position: '課長',
    email: 'kobayashi@finance.co.jp',
    phone: '03-5555-6666',
    mobile: '080-5555-6666',
    postal_code: '103-0027',
    address: '東京都中央区日本橋5-5-5',
    website: 'https://finance.co.jp',
    employee_id: 'demo-emp-003',
    company_id: 'demo-company-001',
    created_at: new Date(Date.now() - 86400000 * 60).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 60).toISOString(),
    image_url: null,
    tags: ['経理', '請求'],
    memo: '月末に請求書送付',
  },
]

export const DEMO_LOGIN_EVENTS = [
  {
    id: 'demo-login-001',
    created_at: new Date().toISOString(),
    ip_address: '192.168.1.1',
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0',
  },
  {
    id: 'demo-login-002',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    ip_address: '192.168.1.1',
    user_agent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0) Safari/605.1.15',
  },
]

export function isDemoMode(): boolean {
  return process.env.NEXT_PUBLIC_DEMO_MODE === 'true'
}
