// Auto-generated by Supabase MCP on 2026-05-22.
// Do not edit by hand. Re-run via Supabase MCP `generate_typescript_types` after schema changes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      access_log: {
        Row: {
          action: string
          business_card_id: string
          employee_id: string | null
          id: number
          occurred_at: string
        }
        Insert: {
          action: string
          business_card_id: string
          employee_id?: string | null
          id?: number
          occurred_at?: string
        }
        Update: {
          action?: string
          business_card_id?: string
          employee_id?: string | null
          id?: number
          occurred_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "access_log_business_card_id_fkey"
            columns: ["business_card_id"]
            isOneToOne: false
            referencedRelation: "business_cards"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "access_log_employee_id_fkey"
            columns: ["employee_id"]
            isOneToOne: false
            referencedRelation: "employees"
            referencedColumns: ["id"]
          },
        ]
      }
      business_cards: {
        Row: {
          address: string | null
          address_building: string | null
          address_city: string | null
          address_line: string | null
          address_postal_code: string | null
          address_prefecture: string | null
          address_raw: string | null
          company_id: string
          company_name: string | null
          company_name_kana: string | null
          created_at: string | null
          department: string | null
          email: string | null
          facebook: string | null
          fax: string | null
          full_name: string | null
          full_name_kana: string | null
          id: string
          image_url: string | null
          is_favorite: boolean | null
          is_private: boolean
          last_contacted_at: string | null
          last_validation_at: string | null
          linkedin: string | null
          mobile: string | null
          name: string | null
          name_kana: string | null
          notes: string | null
          ocr_confidence: number | null
          ocr_raw_text: string | null
          owner_employee_id: string | null
          phone: string | null
          position: string | null
          postal_code: string | null
          relationship_strength: number | null
          relationship_type: string | null
          scanned_at: string | null
          source: string
          tags: string[] | null
          twitter: string | null
          updated_at: string | null
          user_id: string
          validation_score: number | null
          website: string | null
        }
        Insert: {
          address?: string | null
          address_building?: string | null
          address_city?: string | null
          address_line?: string | null
          address_postal_code?: string | null
          address_prefecture?: string | null
          address_raw?: string | null
          company_id: string
          company_name?: string | null
          company_name_kana?: string | null
          created_at?: string | null
          department?: string | null
          email?: string | null
          facebook?: string | null
          fax?: string | null
          full_name?: string | null
          full_name_kana?: string | null
          id?: string
          image_url?: string | null
          is_favorite?: boolean | null
          is_private?: boolean
          last_contacted_at?: string | null
          last_validation_at?: string | null
          linkedin?: string | null
          mobile?: string | null
          name?: string | null
          name_kana?: string | null
          notes?: string | null
          ocr_confidence?: number | null
          ocr_raw_text?: string | null
          owner_employee_id?: string | null
          phone?: string | null
          position?: string | null
          postal_code?: string | null
          relationship_strength?: number | null
          relationship_type?: string | null
          scanned_at?: string | null
          source?: string
          tags?: string[] | null
          twitter?: string | null
          updated_at?: string | null
          user_id: string
          validation_score?: number | null
          website?: string | null
        }
        Update: {
          address?: string | null
          address_building?: string | null
          address_city?: string | null
          address_line?: string | null
          address_postal_code?: string | null
          address_prefecture?: string | null
          address_raw?: string | null
          company_id?: string
          company_name?: string | null
          company_name_kana?: string | null
          created_at?: string | null
          department?: string | null
          email?: string | null
          facebook?: string | null
          fax?: string | null
          full_name?: string | null
          full_name_kana?: string | null
          id?: string
          image_url?: string | null
          is_favorite?: boolean | null
          is_private?: boolean
          last_contacted_at?: string | null
          last_validation_at?: string | null
          linkedin?: string | null
          mobile?: string | null
          name?: string | null
          name_kana?: string | null
          notes?: string | null
          ocr_confidence?: number | null
          ocr_raw_text?: string | null
          owner_employee_id?: string | null
          phone?: string | null
          position?: string | null
          postal_code?: string | null
          relationship_strength?: number | null
          relationship_type?: string | null
          scanned_at?: string | null
          source?: string
          tags?: string[] | null
          twitter?: string | null
          updated_at?: string | null
          user_id?: string
          validation_score?: number | null
          website?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "business_cards_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "business_cards_owner_employee_id_fkey"
            columns: ["owner_employee_id"]
            isOneToOne: false
            referencedRelation: "employees"
            referencedColumns: ["id"]
          },
        ]
      }
      companies: {
        Row: {
          created_at: string
          domain: string
          id: string
          name: string
          plan: string
        }
        Insert: {
          created_at?: string
          domain: string
          id?: string
          name: string
          plan?: string
        }
        Update: {
          created_at?: string
          domain?: string
          id?: string
          name?: string
          plan?: string
        }
        Relationships: []
      }
      employees: {
        Row: {
          activated_at: string | null
          auth_user_id: string | null
          company_id: string
          display_name: string | null
          email: string
          id: string
          invited_at: string
          invited_by: string | null
          role: string
          status: string
        }
        Insert: {
          activated_at?: string | null
          auth_user_id?: string | null
          company_id: string
          display_name?: string | null
          email: string
          id?: string
          invited_at?: string
          invited_by?: string | null
          role?: string
          status?: string
        }
        Update: {
          activated_at?: string | null
          auth_user_id?: string | null
          company_id?: string
          display_name?: string | null
          email?: string
          id?: string
          invited_at?: string
          invited_by?: string | null
          role?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "employees_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "employees_invited_by_fkey"
            columns: ["invited_by"]
            isOneToOne: false
            referencedRelation: "employees"
            referencedColumns: ["id"]
          },
        ]
      }
      import_jobs: {
        Row: {
          company_id: string
          completed_at: string | null
          created_at: string
          employee_id: string | null
          engine: string
          error_message: string | null
          failed_items: number
          id: string
          input_type: string
          processed_items: number
          status: string
          total_items: number
        }
        Insert: {
          company_id: string
          completed_at?: string | null
          created_at?: string
          employee_id?: string | null
          engine: string
          error_message?: string | null
          failed_items?: number
          id?: string
          input_type: string
          processed_items?: number
          status?: string
          total_items?: number
        }
        Update: {
          company_id?: string
          completed_at?: string | null
          created_at?: string
          employee_id?: string | null
          engine?: string
          error_message?: string | null
          failed_items?: number
          id?: string
          input_type?: string
          processed_items?: number
          status?: string
          total_items?: number
        }
        Relationships: [
          {
            foreignKeyName: "import_jobs_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "import_jobs_employee_id_fkey"
            columns: ["employee_id"]
            isOneToOne: false
            referencedRelation: "employees"
            referencedColumns: ["id"]
          },
        ]
      }
      import_results: {
        Row: {
          business_card_id: string | null
          extracted_json: Json | null
          id: string
          job_id: string
          page_or_row: number | null
          status: string
          validation_json: Json | null
        }
        Insert: {
          business_card_id?: string | null
          extracted_json?: Json | null
          id?: string
          job_id: string
          page_or_row?: number | null
          status?: string
          validation_json?: Json | null
        }
        Update: {
          business_card_id?: string | null
          extracted_json?: Json | null
          id?: string
          job_id?: string
          page_or_row?: number | null
          status?: string
          validation_json?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "import_results_business_card_id_fkey"
            columns: ["business_card_id"]
            isOneToOne: false
            referencedRelation: "business_cards"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "import_results_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "import_jobs"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: { [_ in never]: never }
    Functions: {
      current_company_id: { Args: never; Returns: string }
      current_employee: {
        Args: never
        Returns: {
          activated_at: string | null
          auth_user_id: string | null
          company_id: string
          display_name: string | null
          email: string
          id: string
          invited_at: string
          invited_by: string | null
          role: string
          status: string
        }
      }
    }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}
